name: LinkedIn activity workflow
on:
  schedule:
    # Runs each day
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://towardsdatascience.com/pymoode-differential-evolution-in-python-78e4221e5cbe"
